=== api-evangelist/cardano/json-schema/address-content-total.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://cardano.blockfrost.io/schema/address_content_total",
  "title": "Address Content Total",
  "type": "object",
  "properties": {
    "address": {
      "type": "string",
      "description": "Bech32 encoded address",
      "example": "addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz"
    },
    "received_sum": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "The sum of all the UTXO per asset",
        "properties": {
          "unit": {
            "type": "string",
            "format": "Lovelace or concatenation of asset policy_id and hex-encoded asset_name",
            "description": "The unit of the value"
          },
          "quantity": {
            "type": "string",
            "description": "The quantity of the unit"
          }
        },
        "required": [
          "unit",
          "quantity"
        ]
      },
      "example": [
        {
          "unit": "lovelace",
          "quantity": "42000000"
        },
        {
          "unit": "b0d07d45fe9514f80213f4020e5a61241458be626841cde717cb38a76e7574636f696e",
          "quantity": "12"
        }
      ]
    },
    "sent_sum": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "The sum of all the UTXO per asset",
        "properties": {
          "unit": {
            "type": "string",
            "format": "Lovelace or concatenation of asset policy_id and hex-encoded asset_name",
            "description": "The unit of the value"
          },
          "quantity": {
            "type": "string",
            "description": "The quantity of the unit"
          }
        },
        "required": [
          "unit",
          "quantity"
        ]
      },
      "example": [
        {
          "unit": "lovelace",
          "quantity": "42000000"
        },
        {
          "unit": "b0d07d45fe9514f80213f4020e5a61241458be626841cde717cb38a76e7574636f696e",
          "quantity": "12"
        }
      ]
    },
    "tx_count": {
      "type": "integer",
      "example": 12,
      "description": "Count of all transactions on the address"
    }
  },
  "required": [
    "address",
    "received_sum",
    "sent_sum",
    "tx_count"
  ]
}

=== api-evangelist/cardano/examples/address-content-total-example.json
{
  "address": "addr1qxqs59lphg8g6qndelq8xwqn60ag3aeyfcp33c2kdp46a09re5df3pzwwmyq946axfcejy5n4x0y99wqpgtp2gd0k09qsgy6pz",
  "received_sum": [
    {
      "unit": "string",
      "quantity": "string"
    }
  ],
  "sent_sum": [
    {
      "unit": "string",
      "quantity": "string"
    }
  ],
  "tx_count": 12
}
