=== api-evangelist/cardano/json-schema/CertificateListItemMessage.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://cardano.blockfrost.io/schema/CertificateListItemMessage",
  "title": "Certificatelistitemmessage",
  "description": "CertificateListItemMessage represents an item of a list of Mithril certificates",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "hash",
    "previous_hash",
    "epoch",
    "signed_entity_type",
    "metadata",
    "protocol_message",
    "signed_message",
    "aggregate_verification_key"
  ],
  "properties": {
    "hash": {
      "description": "Hash of the current certificate",
      "type": "string",
      "format": "bytes"
    },
    "previous_hash": {
      "description": "Hash of the previous certificate",
      "type": "string",
      "format": "bytes"
    },
    "epoch": {
      "$ref": "#/components/schemas/Epoch"
    },
    "beacon": {
      "deprecated": true,
      "allOf": [
        {
          "$ref": "#/components/schemas/CardanoDbBeacon"
        }
      ]
    },
    "signed_entity_type": {
      "$ref": "#/components/schemas/SignedEntityType"
    },
    "metadata": {
      "$ref": "#/components/schemas/CertificateListItemMessageMetadata"
    },
    "protocol_message": {
      "$ref": "#/components/schemas/ProtocolMessage"
    },
    "signed_message": {
      "description": "Hash of the protocol message that is signed by the signer participants",
      "type": "string",
      "format": "bytes"
    },
    "aggregate_verification_key": {
      "description": "Aggregate verification key used to verify the multi signature",
      "type": "string",
      "format": "bytes"
    }
  },
  "example": {
    "hash": "9dc998101590f733f7a50e7c03b5b336e69a751cc02d811395d49618db3ba3d7",
    "previous_hash": "aa2ddfb87a17103bdf15bfb21a2941b3f3223a3c8d710910496c392b14f8c403",
    "epoch": 32,
    "beacon": {
      "network": "mainnet",
      "epoch": 329,
      "immutable_file_number": 7060000
    },
    "signed_entity_type": {
      "MithrilStakeDistribution": 246
    },
    "metadata": {
      "network": "mainnet",
      "version": "0.1.0",
      "parameters": {
        "k": 5,
        "m": 100,
        "phi_f": 0.65
      },
      "initiated_at": "2022-07-17T18:51:23.192811338Z",
      "sealed_at": "2022-07-17T18:51:35.830832580Z",
      "total_signers": 3
    },
    "protocol_message": {
      "message_parts": {
        "snapshot_digest": "6367ee65d0d1272e6e70736a1ea2cae34015874517f6328364f6b73930966732",
        "next_aggregate_verification_key": "b132362c3232352c36392c31373133352c31323235392c3235332c3233342c34226d745f636f6d6d69746d656e74223a7b22726f6f74223a5b33382c3382c3138322c3231322c2c363"
      }
    },
    "signed_message": "07ed7c9e128744c1a4797b7eb34c54823cc7a21fc95c19876122ab4bb0fe796d6bba2bc",
    "aggregate_verification_key": "7b232392c3130342c34392c35312c3130332c3136352c37364223a7b22726f6f74223a5b3137392c3135312c3135382c37332c37372c2c3135392c3226d745f636f6d6d69746d656e7"
  }
}

=== api-evangelist/cardano/examples/CertificateListItemMessage-example.json
{
  "hash": "string",
  "previous_hash": "string",
  "epoch": 0,
  "beacon": {},
  "signed_entity_type": {},
  "metadata": {
    "network": "string",
    "version": "string",
    "initiated_at": "2023-01-01T00:00:00Z",
    "sealed_at": "2023-01-01T00:00:00Z",
    "total_signers": 0
  },
  "protocol_message": {},
  "signed_message": "string",
  "aggregate_verification_key": "string"
}
